name: ci
on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Validate workspace structure
        run: |
          test -f index.html
          test -d js
          test -d css
      - name: Success
        run: echo "OK"